In [1]:
mylist=[1,2,3,4,5]

In [2]:
mylist

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
myarr=np.array(mylist)

In [5]:
myarr

array([1, 2, 3, 4, 5])

In [6]:
mymat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [12]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0,5,8)    # gives 8 values within 0 to 5

array([0.        , 0.71428571, 1.42857143, 2.14285714, 2.85714286,
       3.57142857, 4.28571429, 5.        ])

In [15]:
np.eye(4)   # I matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.64711647, 0.24894114, 0.59697639, 0.1417398 , 0.94582946])

In [18]:
np.random.rand(5)

array([0.67712291, 0.20858675, 0.46771267, 0.22405688, 0.79190784])

In [20]:
np.random.rand(4,4)

array([[0.91974433, 0.18773282, 0.08365228, 0.61938212],
       [0.06515662, 0.610429  , 0.09036244, 0.01729768],
       [0.50377939, 0.47582291, 0.24470703, 0.89235372],
       [0.80375348, 0.65788112, 0.14708014, 0.91587697]])

In [21]:
np.random.randn(5)

array([-0.08281258,  0.00675397,  0.51155127, -0.28498314,  1.70265635])

In [22]:
np.random.randint(1,100,10)  # (inclusive,exclusive,number of values)

array([47, 52, 87, 64, 98, 65, 49, 61, 44, 74])

In [25]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr=np.random.randint(0,50,10)
ranarr

array([48,  9, 27,  9, 45, 18, 10, 34,  8, 49])

In [27]:
ranarr

array([48,  9, 27,  9, 45, 18, 10, 34,  8, 49])

In [29]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
,arr=np.arange(126)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [33]:
arr.max()

25

In [34]:
arr.min()

1

In [35]:
arr.argmax()     # returns the index location of the maximum value of the array

24

In [36]:
arr.argmin()

0

In [38]:
arr.shape

(25,)

In [40]:
arr=arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int32')

In [43]:
# array operatiins

In [45]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr+arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [48]:
arr*arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [49]:
arr+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [50]:
arr**2  # arr^2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [51]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [52]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [53]:
np.max(arr)

10

In [54]:
np.min(arr)

1

In [55]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [56]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])